# Generated by Django 3.1.3 on 2020-12-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contanct',
            new_name='Contact',
        ),
    ]
